---
title: " "
pagetitle: "Median Household Income"
knit: (function(inputFile, encoding) {
      out_dir <- "output-visuals";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
---
<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r library setup, include=FALSE}
# devtools::install_github("psrc/psrcplot",
#                          force=TRUE)
library(tidyverse)
library(psrcelmer)
library(psrccensus)
library(psrcplot)
library(psrctrends)
library(rlang) #required for psrccensus
library(emmeans) #required for rlang
library(magrittr)
library(kableExtra)
library(ggplot2)

library(summarytools) #freq
library(vtable) #summary stats
library(table1)  #nice descriptive summary table
library(scales) #number formatting
library(ggpubr) #graphing - ggarrange fx
library(forcats) #for factor re-leveling
library(plotly) #for interactive charts

library(odbc) #connect to ElmerGeo
library(DBI) #connect to ElmerGeo
library(sf)
library(leaflet)
library(leafem) #home button
library(htmlwidgets) #save visuals as html
library(raster)
library(ggspatial)
library(lubridate) #year formatting
library(stringr) #add leading zero's
library(reshape2) #formatting data
library(readxl)
library(RColorBrewer)
library(gridExtra)

install_psrc_fonts()
library(showtext) #trying to fix PSRC font issues
library(sysfonts) #required for showtext
library(showtextdb) #required for showtext

library(echarts)
library(echarts4r)
# remotes::install_github("JohnCoene/echarts",
#                         force=TRUE)
# remotes::install_github("JohnCoene/echarts4r",
#                         force=TRUE)
library(echarts4r.assets)
```

```{r setup, include=FALSE}
source("C:/Users/mrichards/Documents/GitHub/equity-tracker-charts/equity-tracker-chart-functions.R")

# Load data
# PUMS/OSPI data set
pums_ospi_elmer <- get_table(schema="equity", tbl_name="v_tracker_indicators")


indicator_measure <- 'median_household_income'
indicator_title <- 'Median household income'

# clean data set
data_full <- pums_ospi_elmer %>% 
  # distinct(indicator_fact_id, .keep_all = TRUE) %>%
  dplyr::filter(indicator_type==indicator_measure) %>% 
  dplyr::filter(focus_type!="Total") %>% 
  filter(focus_attribute!="Total") %>%
  filter(indicator_attribute!="Total") %>%
  dplyr::mutate(data_year_yr=format(data_year,format="%Y")) 

# renaming labels ----
# data_clean <- data_full %>% 
#   mutate(focus_type_edit = case_when(focus_type=="POC_cat"~"Race/Ethnicity",
#                                      focus_type=="Disability_cat"~"Disability Status",
#                                      focus_type=="LEP_cat"~"English Proficiency",
#                                      focus_type=="Income_cat"~"Low Income",
#                                      focus_type=="Youth_cat"~"Households with Youth <18",
#                                      focus_type=="Older_cat"~"Households with Older Adults 65+"))
data_clean <- data_full %>% 
  mutate(focus_type_edit = case_when(focus_type=="POC_cat"~"People of Color",
                                     focus_type=="Disability_cat"~"People with a Disability",
                                     focus_type=="LEP_cat"~"People with Limited English Proficiency",
                                     focus_type=="Income_cat"~"Households with Lower Income",
                                     focus_type=="Youth_cat"~"Households with Youth <18",
                                     focus_type=="Older_cat"~"Households with Older Adults 65+"),
         focus_attribute_edit = case_when(focus_attribute== "POC"~ "People of color",
                                          focus_attribute== "Non-POC"~ "White non-Hispanic",
                                          focus_attribute== "Low Income"~ "Households with lower income",
                                          focus_attribute== "Non-Low Income"~ "Other households",
                                          focus_attribute== "With disability"~ "With a disability",
                                          focus_attribute== "Without disability"~ "Without a disability",
                                          focus_attribute== "Limited English proficiency"~ "Limited English proficiency",
                                          focus_attribute== "English proficient"~ "English proficient",
                                          focus_attribute== "Household with youth"~ "Households with youth",
                                          focus_attribute== "Household without youth"~ "Other households 2",
                                          focus_attribute== "Household with older adult"~ "Households with older adults",
                                          focus_attribute== "Household without older adult"~ "Other households 3"))



# re-ordering variables ----

# data_clean$focus_type_ord <- factor(data_clean$focus_type_edit,
#                                     levels = c("Race/Ethnicity",
#                                                "Low Income",
#                                                "Disability Status",
#                                                "English Proficiency",
#                                                "Households with Youth <18",
#                                                "Households with Older Adults 65+"))
data_clean$focus_type_ord <- factor(data_clean$focus_type_edit,
                                    levels = c("People of Color", 
                                               "Households with Lower Income", 
                                               "People with a Disability",
                                               "People with Limited English Proficiency", 
                                               "Households with Youth <18", 
                                               "Households with Older Adults 65+"))
# data_clean$focus_attribute_ord <- factor(data_clean$focus_attribute,
#                                          levels = c("POC",
#                                                     "Non-POC",
#                                                     "Low Income",
#                                                     "Non-Low Income",
#                                                     "With disability",
#                                                     "Without disability",
#                                                     "Limited English proficiency",
#                                                     "English proficient",
#                                                     "Household with youth",
#                                                     "Household without youth",
#                                                     "Household with older adult",
#                                                     "Household without older adult",
#                                                     "Total"))
data_clean$focus_attribute_ord <- factor(data_clean$focus_attribute_edit,
                                         levels = c("People of color", "White non-Hispanic",
                                                    "Households with lower income", "Other households",
                                                    "With a disability", "Without a disability",
                                                    "Limited English proficiency", "English proficient",
                                                    "Households with youth", "Other households 2",
                                                    "Households with older adults", "Other households 3"))
data_clean$county_ord <- factor(data_clean$county,
                                levels = c("King",
                                           "Kitsap",
                                           "Pierce",
                                           "Snohomish",
                                           "Region"))



# Order for various factors
quintile_order <- c("Low", "Low\nMedium", "Medium", "Medium\nHigh", "High")

county_order <- c("King", "Kitsap", "Pierce", "Snohomish", "Region")

# efa_order <- c("Race/Ethnicity", "Low Income", "Disability Status", 
#                "English Proficiency", "Households with Youth <18", 
#                "Households with Older Adults 65+")

efa_order <- c("People of Color", "Households with Lower Income", "People with a Disability", 
               "People with Limited English Proficiency", "Households with Youth <18", 
               "Households with Older Adults 65+")

# focus_attribute_order <- c("POC", "Non-POC", "Low Income", "Non-Low\nIncome", 
#                            "With\ndisability", "Without\ndisability",
#                            "Limited\nEnglish\nproficiency", "English\nproficient",
#                            "Household\nwith youth", "Household\nwithout\nyouth",
#                            "Household\nwith older\nadult", "Household\nwithout\nolder adult")

focus_attribute_order <- c("People of\ncolor", "White\nnon-Hispanic", 
                           "Households with\nlower income", "Other\nhouseholds", 
                           "With a\ndisability", "Without a\ndisability",
                           "Limited\nEnglish\nproficiency", "English\nproficient",
                           "Households\nwith youth", "Other\nhouseholds 2",
                           "Households\nwith older\nadult", "Other\nhouseholds 3")

data_clean <- data_clean %>%
  arrange(county_ord, focus_type_ord, focus_attribute_ord)

chart <- equity_tracker_column_facet(df = data_clean,
                                     geo = "county_ord",
                                     x = "focus_attribute_ord",
                                     y = "fact_value",
                                     facet = "focus_type_ord",
                                     title = "Median Household Income",
                                     y_min = 0,
                                     y_max = 180000,
                                     dec = 0,
                                     esttype = "currency",
                                     color = "purples")

```
<p style="font-family: Poppins; font-size:14pt; font-weight:bold">
Median Household Income  
</p>
<p style="font-family: Poppins; font-size:12pt; font-weight:normal">
values are adjusted to 2021 dollars  
</p>
```{r chart, echo=FALSE}
chart
```
<p style="font-family: Poppins; font-size:10pt; font-style:italic">
Source: U.S. Census Bureau, American Community Survey (ACS) 5-Year Public Use Microdata Sample (PUMS)
</p> 